sudo: required
language: ruby
env:
  global:
  - IMAGE_NAME=consumerdatastandardsaustralia/engineering
services:
- docker
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
after_success:
  - sonar-scanner -Dsonar.projectKey=ConsumerDataStandardsAustralia_engineering  -Dsonar.organization=consumerdatastandardsaustralia  -Dsonar.sources=.  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login="$SONARCLOUD_LOGIN"
  - ".travis/push.sh"
