sudo: required
language: ruby
env:
  global:
  - IMAGE_NAME=consumerdatastandardsaustralia/engineering
services:
- docker
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
- rm -fr * 
- touch .nojekyll
- docker run $IMAGE_NAME tar -c -C /opt/engineering/build/html | tar x
after_success:
- ".travis/push.sh"
